---------------------------------------------------- sync from git://git.openembedded.org/meta-openembedded(branch dunfell) in 2021-04-09 last commit
commit 430ef96fe65f62d8da995f446d5b9b093544f031 (HEAD -> dunfell, origin/dunfell-next, origin/dunfell)
Author: Armin Kuster <akuster808@gmail.com>
Date:   Sun Apr 4 03:09:16 2021 +0000

    wireguard: fix build issue with updated 5.4 kernel

     error: static declaration of 'icmp_ndo_send' follows non-static declaration
     |   959 | static inline void icmp_ndo_send(struct sk_buff *skb_in, int type, int code, __be32 info)
     |       |                    ^~~~~~~~~~~~~

    Signed-off-by: Armin Kuster <akuster808@gmail.com>